---
- name: "Add PP User & Password"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Get PP Token"
      uri:
        method: POST
        url: "https://{{ PP_URL }}/OAuth2/Token"
        body:
          grant_type: password
          username: "{{ API_User }}"
          password: "{{ API_Password }}"
        body_format: form-urlencoded
        validate_certs: no
      register: API

    - set_fact:
        PP_Token: "{{ API.json.access_token }}"

    - name: "Get Client Username Info"
      uri:
        method: GET
        url: "https://{{ PP_URL }}/api/v4/rest/credential/{{ RecordID }}"
        headers:
          Content-Type: "application/json"
          Cache-Control: "no-cache"
          Authorization: "Bearer {{ PP_Token }}"
        validate_certs: no
      register: PP_API_Info

    - name: "Get PP Folder"
      set_fact:
        PP_User: "{{ PP_API_Info.json.Username }}"

    - name: "Get Client Password Info"
      uri:
        method: GET
        url: "https://{{ PP_URL }}/api/v4/rest/credential/{{ RecordID }}/password"
        headers:
          Content-Type: "application/json"
          Cache-Control: "no-cache"
          Authorization: "Bearer {{ PP_Token }}"
        validate_certs: no
      register: PP_Pass
    
    - name: Print User
      debug:
        msg: "RUNDECK:DATA:SECURE:username={{ PP_User }}"

    - name: Print Pass
      debug:
        msg: "RUNDECK:DATA:SECURE:password={{ PP_Pass.json }}"